# Functions for generating camtrapReport ecological reports
# Licence: MIT
#--------

setGeneric(
  "report",
  function(object, filename, view, test) {
    methods::standardGeneric("report")
  }
)
.generate_report <- function(object, output_file, rmd_file) {
  object$generateReport(
    output_file = output_file,
    rmd_file = rmd_file
  )
}

#' Generate ecological and data-status reports
#'
#' Generate automated HTML reports from a [`camReport`][camReport-classes]
#' object. `report()` creates an ecological report, while [status()] creates a
#' data-status report summarising data completeness, structure, and quality.
#'
#' Both functions create an intermediate R Markdown file and render it to HTML.
#' By default, `report()` creates `report.html` and `report.Rmd`, while
#' `status()` creates `data_status.html` and `data_status.Rmd`.
#'
#' The ecological report is generated from the report modules attached to the
#' `camReport` object. The data-status report is generated from status modules
#' that summarise key aspects of the dataset, including spatial, temporal,
#' annotation, validation, and species-level information.
#'
#' If `test = TRUE` is used with `report()`, the package attempts to test report
#' modules when rendering fails. This can help identify modules that cause
#' errors during report generation.
#'
#' @param object A [`camReport`][camReport-classes] object created by
#'   [camData()].
#' @param filename An optional character string giving the output filename or
#'   file path without an extension. The default is `"report"` for `report()`
#'   and `"data_status"` for `status()`. Relative default filenames are written
#'   to the camera-trap data directory.
#' @param view A logical value (default `FALSE`) specifying whether the
#' generated
#'   HTML report is opened after rendering.
#' @param test A logical value (default `FALSE`). If `TRUE`, report modules are
#'   tested when ecological report generation fails, helping identify
#'   problematic modules.
#'
#' @return Invisibly returns the path to the generated HTML report.
#'
#' @seealso [camData()], [reportSection()], [updateReportSection()],
#'   [section_names()]
#' @family report generation
#'
#' @usage
#' report(object, filename, view, test)
#'
#' status(object, filename, view)
#' @name report
#' @aliases report status report,camReport-method status,camReport-method
#'
#' @examples
#' \donttest{
#' if (rmarkdown::pandoc_available()) {
#' source_dataset <- system.file(
#'   "external",
#'   "dataset",
#'   package = "camtrapReport"
#' )
#' example_dataset <- tempfile("camtrapReport-example-")
#' dir.create(example_dataset)
#' invisible(file.copy(
#'   list.files(source_dataset, full.names = TRUE),
#'   example_dataset,
#'   recursive = TRUE
#' ))
#'
#' cm <- camData(example_dataset)
#'
#' # Use one lightweight section for the ecological report
#' cm <- sections(cm, "introduction")
#'
#' # Generate an ecological report in a temporary directory
#' report_stem <- tempfile("camtrapReport-report-")
#' report_file <- report(
#'   cm,
#'   filename = report_stem,
#'   view = FALSE
#' )
#'
#' file.exists(report_file)
#'
#' # Remove files generated by the examples
#' unlink(c(
#'   report_file,
#'   paste0(report_stem, ".Rmd"),
#'   example_dataset
#' ), recursive = TRUE, force = TRUE)
#' }
#' }
setMethod(
  "report",
  signature(object = "camReport"),
  function(object, filename = "report", view, test) {
    
    if (missing(view)) view <- FALSE
    if (missing(test)) test <- FALSE
    
    # Resolve requested filename
    if (missing(filename) || is.null(filename) || !nzchar(filename)) {
      filename <- "report"
      fi <- NULL
    } else {
      fi <- .file_info(filename)
      filename <- fi$filename
      if (identical(fi$path, ".")) fi <- NULL
    }
    
    # Resolve base output directory
    base_dir <- object$info$directory
    
    base_dir <- tryCatch(
      normalizePath(base_dir, winslash = "/", mustWork = TRUE),
      error = function(e) {
        getwd()
      }
    )
    
    # Decide final output stem
    if (is.null(fi)) {
      out_stem <- file.path(base_dir, filename)
    } else {
      out_dir <- tryCatch(
        normalizePath(fi$path, winslash = "/", mustWork = TRUE),
        error = function(e) {
          warning(
            'The directory specified in "filename" ("', fi$path,
            '") does not exist; the default path is used instead.'
          )
          base_dir
        }
      )
      out_stem <- file.path(out_dir, filename)
    }
    
    # Generate report
    w <- try(
      .generate_report(
        object = object,
        output_file = paste0(out_stem, ".html"),
        rmd_file = paste0(out_stem, ".Rmd")
      ),
      silent = TRUE
    )
    
    if (inherits(w, "try-error")) {
      
      if (test) {
        
        message("\nTesting of modules is started....")
        
        ww <- which(is.na(object$reportObjectElements$Modules_info$tested))
        
        if (length(ww) > 0) {
          temp_path <- file.path(object$info$directory, "_temp")
          
          dir.create(
            temp_path,
            showWarnings = FALSE
          )
          
          if (dir.exists(temp_path)) {
            .path <- temp_path
          } else {
            .path <- NULL
          }
          
          n <- object$reportObjectElements$Modules_info$name[ww]
          
          for (nn in n) {
            .w <- .QuickTestReportSection(
              object$reportObjectElements$Modules[[nn]],
              object,
              path = .path
            )
            
            object$reportObjectElements$Modules_info$tested[
              object$reportObjectElements$Modules_info$name == nn
            ] <- .w
          }
          
          .attach_modules(
            object,
            n = object$reportObjectElements$Modules_info$name[
              which(object$reportObjectElements$Modules_info$tested)
            ]
          )
          
          message(
            "\nTesting is done; the modules are attached, and the report ",
            "generation is started...!"
          )
          
          return(report(object, filename = filename, view = view, test = FALSE))
          
        } else {
          
          if (!all(object$reportObjectElements$Modules_info$tested)) {
            
            .attach_modules(
              object,
              n = object$reportObjectElements$Modules_info$name[
                which(object$reportObjectElements$Modules_info$tested)
              ]
            )
            
            return(report(
              object,
              filename = filename,
              view = view,
              test = FALSE
            ))
            
          } else {
            stop("Although all sections are tested, the report cannot be ", "generated...!")
          }
        }
        
      } else {
        
        message(
          "Report generation is stopped because of an error; add `test = ",
          "TRUE` to exclude the modules that cause error!"
        )
        
        return(w)
      }
    }
    
    if (isTRUE(view)) {
      
      out <- paste0(out_stem, ".html")
      
      message(
        "Report generated at: ",
        normalizePath(out, winslash = "/", mustWork = FALSE)
      )
      
      viewer <- getOption("viewer")
      
      if (!is.null(viewer)) {
        viewer(out)
      } else {
        utils::browseURL(out)
      }
    }
    
    invisible(paste0(out_stem, ".html"))
  }
)
