on:
  pull_request:

name: render-docs-artifact.yaml

permissions: read-all

jobs:
  render-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::devtools, any::pkgdown, any::rmarkdown
          needs: website

      - name: Build generated documentation
        shell: Rscript {0}
        run: |
          devtools::document()
          rmarkdown::render(
            "README.Rmd",
            output_format = "github_document",
            output_file = "README.md",
            quiet = TRUE
          )
          pkgdown::build_site(new_process = FALSE)

      - name: Upload generated documentation
        uses: actions/upload-artifact@v7
        with:
          name: generated-documentation
          path: |
            README.md
            NAMESPACE
            man
            docs
